# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      app-dependencies:
        depedency-type: "app"
        applies-to: version-updates
        exclude-patterns:
          - "bandit"
          - "pytest*"
          - "ruff"
          - "coverage-badge"
          - "mkdocs-click"
      test-dependencies:
        dependency-type: "test"
        applies-to: version-updates
        pattern:
          - "bandit"
          - "pytest*"
          - "ruff"
          - "coverage-badge"
        exclude-patterns:
          - "mkdocs-click"
