---
red:
  red_user_id: 12345
  red_api_key: 1234notarealapikey
  red_api_retries: 3
  red_api_seconds_between_calls: 5
  search:
    use_release_type: true
    use_first_release_year: true
    use_record_label: false
    use_catalog_number: false
    enable_api_cache: true
    use_fl_tokens: false
  snatches:
    snatch_directory: /app/tests/resources
    snatch_recs: true
    skip_prior_snatches: true
    max_size_gb: 2.0
  format_preferences:
    - format: "FLAC"
      encoding: "24bit+Lossless"
      media: "SACD"
    - format: "FLAC"
      encoding: "24bit+Lossless"
      media: "WEB"
    - format: "FLAC"
      encoding: "Lossless"
      media: "CD"
      cd_only_extras:
        log: 100
        has_cue: true
    - format: "FLAC"
      encoding: "Lossless"
      media: "CD"
      cd_only_extras:
        log: 100
        has_cue: false
    - format: "FLAC"
      encoding: "Lossless"
      media: "CD"
      cd_only_extras:
        log: 0
        has_cue: false
    - format: "MP3"
      encoding: "V0+(VBR)"
      media: "ANY"
lfm:
  lfm_api_key: 5678alsonotarealapikey
  lfm_username: fake-username
  lfm_password: fake-password
  lfm_api_retries: 3
  lfm_api_seconds_between_calls: 2
  rec_types_to_scrape: [album, track]
  allow_library_items: false
  enable_scraper_cache: true
musicbrainz:
  musicbrainz_api_max_retries: 3
  musicbrainz_api_seconds_between_calls: 1
