# This is an example of the minimal required YAML config with dummy placeholder values, 
# and with all non-required fields omitted.
#
# For full configuration reference details, see the following link:
# https://github.com/windexvalence/last-red-recs/blob/main/docs/configuration_reference.md
---
red:
  red_user_id: 12345
  red_api_key: 1234notarealapikey
last_fm:
  last_fm_api_key: 5678alsonotarealapikey
  last_fm_username: fake-username
  last_fm_password: fake-password

search:
  # NOTE: the output_summary_filepath should point to a directory 
  # which is mounted by the container and exists on your host machine.
  output_summary_filepath: /some/other/fake/file.tsv

snatches:
  # NOTE: the snatch_directory must point to a directory 
  # which is mounted by the container and exists on your host machine.
  snatch_directory: /app/tests/resources
  snatch_recs: true
  max_size_gb: 2.0

format_preferences:
  - preference:
      format: "FLAC"
      encoding: "Lossless"
      media: "CD"
      cd_only_extras:
        log: 100
        has_cue: true
# Feel free to add and/or modify this list of preferences however you want.
# Refer to https://github.com/windexvalence/last-red-recs/blob/main/docs/configuration_reference.md for more details.
