name: Build
run-name: Build ${{ github.ref }} by ${{ github.actor }}
on: 
  push:
    branches:
      - '**'
    tags-ignore: 
      - 'v*'
env:
  IMAGE_REGISTRY: ghcr.io
  TEST_IMAGE_NAME: ${{ github.repository }}-test
jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "Repo code checked out from branch ${{ github.ref }}"
      - name: Build Image Without Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.TEST_IMAGE_NAME }}:${{ github.run_number }}-test
          target: plastered-test
      - name: UV lockfile check
        run: |
          docker run -t --rm --entrypoint bash ${{ env.TEST_IMAGE_NAME }}:${{ github.run_number }}-test -c 'uv lock --check'
      - name: Run Static Code Checks
        run: |
          docker run -t --rm -e CODE_FORMAT_CHECK=1 -e GITHUB_ACTIONS=1 --entrypoint /app/build_scripts/code-format.sh ${{ env.TEST_IMAGE_NAME }}:${{ github.run_number }}-test
          docker run -t --rm -e GITHUB_ACTIONS=1 --entrypoint bash ${{ env.TEST_IMAGE_NAME }}:${{ github.run_number }}-test -c 'mypy --config-file /app/pyproject.toml /app'
      - name: Run Unit Tests
        run: |
          docker run -t -e GITHUB_ACTIONS=1 --rm --entrypoint /app/tests/tests_entrypoint.sh ${{ env.TEST_IMAGE_NAME }}:${{ github.run_number }}-test tests
