name: Build and Test
run-name: Build and Test ${{ github.ref }} by ${{ github.actor }}
on: [push]
jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy step triggered by a ${{ github.even_name }} event on branch ${{ github.ref }}."
      - run: echo "Running on a ${{ runner.os }} server."
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "Repo code checked out from branch ${{ github.ref }}"
      - name: List files in repo
        run: ls ${{ github.workspace }}
      - name: Build Image Without Push
        uses: docker/build-push-action@v6
        with:
          tags: last-red-recs:${{ github.run_number }}
      - name: Code Format Check
        run: |
          docker run -t --rm -e CODE_FORMAT_CHECK=1 -e GITHUB_ACTIONS=1 --entrypoint /app/build_scripts/code-format.sh last-red-recs:${{ github.run_number }}
      - name: Decrypt Test HTML Assets
        run: ./build_scripts/gh_action_decrypt_test_html.sh
        env:
          TEST_HTML_PASSPHRASE: ${{ secrets.TEST_HTML_PASSPHRASE }}
      - name: Run Unit Tests
        run: |
          docker run -t -v ./tests/resources:/app/tests/resources --rm --entrypoint /app/tests/tests_entrypoint.sh last-red-recs:${{ github.run_number }}
