name: Release
run-name: Release ${{ github.ref }}
env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
on:
  push:
    tags:
      - "v*"

# permissions:
#   contents: write

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
  release:
    runs-on: ubuntu-latest
    needs: build-and-test-image
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Image Without Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Code Format Check
        run: |
          docker run -t --rm -e CODE_FORMAT_CHECK=1 -e GITHUB_ACTIONS=1 --entrypoint /app/build_scripts/code-format.sh ${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Decrypt Test HTML Assets
        run: ./build_scripts/gh_action_decrypt_test_html.sh
        env:
          TEST_HTML_PASSPHRASE: ${{ secrets.TEST_HTML_PASSPHRASE }}
      - name: Run Unit Tests
        run: |
          docker run -t -e GITHUB_ACTIONS=1 -v ./tests/resources:/app/tests/resources --rm --entrypoint /app/tests/tests_entrypoint.sh ${{ env.IMAGE_NAME }}:${{ github.run_number }} tests
      - name: Tag Release  # TODO: after initial main tag, use https://github.com/marketplace/actions/get-latest-tag for tag calculation
        run: echo "TODO implement in followup PR"
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: BUILD_ENV=release
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ github.run_number }},${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:0.0.2,${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
  
  # create-release:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Create release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         tag: ${{ github.ref_name }}
  #       run: |
  #         gh release create "$tag" \
  #             --repo="$GITHUB_REPOSITORY" \
  #             --title="${tag#v}" \
  #             --generate-notes
